### ISSUE TITLE
Media picker modal should show a message if there is no media in the project 

### ISSUE THREAD

**Issue by willdady** [contentjet/contentjet-ui#2]
Currently when trying to add media from the entry editor screen the media modal simply renders as blank. This could be made more user friendly with some text indicating there is no media in the project.

**Comment by banks117** [comment]
@willdady I would be happy to look into this one.

**Comment by willdady** [comment]
@brandonmbanks go for it. Thanks.

**Comment by banks117** [comment]
Just for visibility, I'm travelling this weekend. But I will be looking at this next week. If anyone wants to grab over the weekend. Go for it.

**Comment by banks117** [comment]
@willdady I'm getting an error trying to spin up the api when I migrate my database. `Error: knex: Required configuration option 'client' is missing.` Looks like it is set in the `app.js` so not sure what the problem is.

**Comment by willdady** [comment]
Pretty sure the problem is you'll need to have `NODE_ENV` set. e.g. `export NODE_ENV=development`. Sorry for any confusion.

**Comment by banks117** [comment]
Thank you sir!
